version: '3'

services:
  db:
    image: postgres
    container_name: data-base
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  application:
    build: ./
    container_name: phone-book
    expose:
      - "9005"
    ports:
      - "9005:9005"
    environment:
      - DATASOURCE_HOST=${DATASOURCE_HOSTNAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
    depends_on:
      - "db"

volumes:
  db-data: